name: NiuNiu
options:
  bundleIdPrefix: app.personal
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.6.5"
    CURRENT_PROJECT_VERSION: "16"
    ARCHS: arm64
    SUPPORTED_PLATFORMS: iphoneos
    ENABLE_BITCODE: NO
    CLANG_ENABLE_MODULES: YES
targets:
  NiuNiu:
    type: application
    platform: iOS
    sources:
      - App
      - path: Vendor/IJK-Licenses
        buildPhase: resources
        type: folder
    dependencies:
      - framework: Vendor/IJKMediaFramework.framework
        embed: true
        codeSign: false
      - sdk: libbz2.tbd
      - sdk: libz.tbd
      - sdk: Security.framework
      - sdk: CoreFoundation.framework
      - sdk: UIKit.framework
      - sdk: MediaPlayer.framework
      - sdk: Foundation.framework
      - sdk: AudioToolbox.framework
      - sdk: AVFoundation.framework
      - sdk: CoreMedia.framework
      - sdk: CoreVideo.framework
      - sdk: VideoToolbox.framework
      - sdk: OpenGLES.framework
      - sdk: QuartzCore.framework
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: 牛牛视频
        CFBundleShortVersionString: "1.6.5"
        CFBundleVersion: "16"
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - audio
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        LSSupportsOpeningDocumentsInPlace: true
        UIFileSharingEnabled: true
        NSLocalNetworkUsageDescription: 搜索同一局域网中的电视并进行DLNA投屏
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: App/NiuNiu-Bridging-Header.h
        PRODUCT_BUNDLE_IDENTIFIER: app.personal.niuniu
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: NO
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
